### PR TITLE
Master

### PR DESCRIPTION
**Pull request by samhuangszu**
can suport this css selector `[property=og:url]`?
url:
http://www.87wx.net/book/88577/

### CODE REVIEW

**Comment by iabudiab** [comment]
@samhuangszu Why is this a Pull Request? Did you mean to open a new issue with a feature request?

**Comment by iabudiab** [comment]
@samhuangszu This selector is already supported.

```
NSURL *url = [NSURL URLWithString:@"http://www.87wx.net/book/88577/"];
NSString *html = [NSString stringWithContentsOfURL:url encoding:NSUTF8StringEncoding error:nil];

HTMLDocument *doc = [HTMLDocument documentWithString:html];
NSArray<HTMLElement *> *elements = [doc querySelectorAll:@"[property='og:url']"];
for (HTMLElement *element in elements) {
  NSLog(@"%@\n", element[@"content"]);
}

// Output
// http://www.87wx.net/88/88577/
```

**Comment by samhuangszu** [comment]
[property=og:url] the selector is some different [property='og:url'], when use [property=og:url] , can't query the target.

**Comment by iabudiab** [comment]
> [property=og:url] the selector is some different [property='og:url'], when use [property=og:url] , can't query the target.

What do you mean by different?

Semantically they are the same, however the `[property=og:url]` selector wont work because it is, strictly speaking, not a valid CSS selector.

`HTMLKit` parses CSS3 Selectors according to the specification, more specifically the section about [Attribute Selectors](https://www.w3.org/TR/selectors-3/#attribute-selectors). An attribute's value is either a [CSS String](https://www.w3.org/TR/CSS21/syndata.html#strings) or a [CSS Identifier](https://www.w3.org/TR/CSS21/syndata.html#value-def-identifier)

You should use a valid selector syntax, which is either:
- Quoted: `[property='og:url']`
- Escaped: `[property=og\:url]` _don't forget to escape the escape in code, i.e. `[property=og\\:url]`_

Let me know if you mean something else. However this PR should be an issue anyway, so closing it here. Please open an issue next time if you're asking for a feature request.

**Pull request closed without merging**
